name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  EB_ENVIRONMENT_NAME: tornado-prediction-env
  EB_APPLICATION_NAME: tornado-prediction-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/ || echo "No tests found"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Install EB CLI
      run: |
        pip install awsebcli
        
    - name: Deploy to Elastic Beanstalk
      run: |
        # Create deployment package
        zip -r deployment.zip . -x "*.git*" "node_modules/*" "__pycache__/*" "*.pyc" ".env*"
        
        # Deploy to Elastic Beanstalk
        eb init ${{ env.EB_APPLICATION_NAME }} --region ${{ env.AWS_REGION }} --platform "Python 3.11"
        eb deploy ${{ env.EB_ENVIRONMENT_NAME }} --region ${{ env.AWS_REGION }}
        
    - name: Update deployment status
      run: |
        echo "Deployment completed successfully!"
        echo "Application URL: http://${{ env.EB_ENVIRONMENT_NAME }}.${{ env.AWS_REGION }}.elasticbeanstalk.com" 